RedditClone/config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                     users GET    /users(.:format)                                                                         users#index
#                           POST   /users(.:format)                                                                         users#create
#                  new_user GET    /users/new(.:format)                                                                     users#new
#                 edit_user GET    /users/:id/edit(.:format)                                                                users#edit
#                      user GET    /users/:id(.:format)                                                                     users#show
#                           PATCH  /users/:id(.:format)                                                                     users#update
#                           PUT    /users/:id(.:format)                                                                     users#update
#                           DELETE /users/:id(.:format)                                                                     users#destroy
#               new_session GET    /session/new(.:format)                                                                   sessions#new
#                   session DELETE /session(.:format)                                                                       sessions#destroy
#                           POST   /session(.:format)                                                                       sessions#create
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: redirect('/users')

  resources :users do 
    resources :subs, only: [:index, :create]
  end

  resource :session, only: [:new, :create, :destroy]
  resources :subs, only: [:new, :show, :edit, :update]
end

RedditClone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RedditClone/app/models/sub.rb
class Sub < ApplicationRecord
    validates :title, :moderator_id, presence: true
end

RedditClone/app/models/user.rb
class User < ApplicationRecord
    
    attr_reader :password

    validates :username, :password_digest, :session_token, presence: true
    validates :password, length: { minimum: 6 }, allow_nil: true
    validates :username, :session_token, uniqueness: true

    after_initialize :ensure_session_token

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)

        user && user.is_password?(password) ? user : nil
    end

    def is_password?(password)
        BCrypt::Password.new(password_digest).is_password?(password)
    end

    def password=(password)
        self.password_digest = BCrypt::Password.create(password)
        @password = password
    end

    def ensure_session_token
        self.session_token ||= SecureRandom::urlsafe_base64
    end

    def reset_session_token!
        self.session_token = SecureRandom::urlsafe_base64
        self.save
        self.session_token
    end
end

RedditClone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #CELLL
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def login!(user)
        session[:session_token] = user.reset_session_token!
    end

    def loggout!
        current_user.reset_session_token!
        session[:session_token] = nil
        current_user = nil
    end

    def logged_in?
        !!current_user
    end

    def ensure_logged_in
        redirect_to new_session_url unless logged_in?
    end
end

RedditClone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :ensure_logged_in, only: [:destroy]

    def new
        render :new
    end

    def create
        @user = User.find_by_credentials(params[:user][:username],params[:user][:password])
    
        if @user
           login!(@user)
           redirect_to users_url 
        else
            flash.now[:errors] = ['Invalid Credentials']
            render :new
        end
    end

    def destroy
        loggout!
        redirect_to new_session_url
    end
end

RedditClone/app/controllers/subs_controller.rb
class SubsController < ApplicationController

    def index
    end

    def new
    end

    def create
    end

    def edit
    end

    def update
    end

    def show
    end

    private

    def sub_params
        params.require(:sub).permit(:title, :description)
    end
end

RedditClone/app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :ensure_logged_in, only: [:show, :destroy]

    def index
        @users = User.all
        render :index
    end

    def new
        @user = User.new
        render :new
    end

    def show
        @user = User.find_by(id: params[:id])
        render :show
    end

    def create
        @user = User.new(user_params)

        if @user.save
            login!(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end    
    end

    # def edit

    # end

    # def update

    # end

    def destroy
        @user = User.find_by(id: params[:id])
        
        if @user == current_user
            @user.destroy
            loggout!
            redirect_to users_url
        else
            flash[:errors] = ['You cannot delete another user!']
            redirect_to users_url
        end
    end

    private

    def user_params
        params.require(:user).permit(:username, :password)
    end
end

RedditClone/app/helpers/application_helper.rb
module ApplicationHelper
end

RedditClone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="../assets/stylesheets/application.css">
  </head>

  <body>
  <header>
    <h1>GeorgeReddit</h1>
    <% unless logged_in? %>
      <div>
        <form action="<%= new_user_url %>" method="GET">
            <input type="submit" value="Sign Up">
        </form>

        <form action="<%= new_session_url %>" method="GET">
            <input type="submit" value="Log In">
        </form>
      </div>
      <% else %>
      <form action="<%= session_url %>" method="POST">
        <input type="hidden" name="_method" value="DELETE">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="submit" value="Log Out">
      </form>
  <% end %>
      </header>
      <div>
        <% if flash[:errors] %>
          <ul>
              <% flash[:errors].each do |error| %>
                  <li><%= error %></li>
              <% end %>
          </ul>
        <% end %>
      </div>
  
     <%= yield %>

     <footer>
      <div>
        <p>GeorgeReddit</p>
      </div>

      <div>
        <p>Copyright 2021</p>
      </div>
     </footer>

</body>
</html>

RedditClone/app/views/users/index.html.erb
<h1>All Users</h1>


    <% @users.each do |user| %>
        <p><a href="<%=user_url(user)%>"><%= user.username %></a></p>
    <% end %>

   

RedditClone/app/views/users/new.html.erb
<h1>Sign Up!</h1>

<form action="<%= users_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label for="username">Username:</label>
    <input id="username" type="text" name="user[username]" value="<%= @user.username %>">

     <label for="password">Password:</label>
    <input id="password" type="password" name="user[password]">

    <input type="submit" value="Sign Up">

</form>

RedditClone/app/views/users/show.html.erb
<h2><%= @user.username %></h2>


<form action="<%= users_url %>" method="GET">
    <input type="submit" value="Back to Index">
</form>

<form action="<%= user_url(@user) %>" method="POST">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="submit" value="Delete Account">
</form>